version: '3'

services:
  xiyan-server:
    image: image_mcp_xiyan_server:1.1
    container_name: docker_xiyan_mcp_server
    working_dir: /app
    environment:
      - YML=/app/config.yml
    volumes:
      - ./src/xiyan_mcp_server:/app
      - mcp_xiyan_server_venv:/app/.venv
    ports:
      - "8012:8012"
    networks:
      - mcp-network
    
    # command: ["python3", "/app/app.py"]
    command: ["tail", "-f", "/dev/null"]
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
    restart: always

  mcp-client:
    image: image_mcp_xiyan_client:1.1
    container_name: docker_xiyan_mcp_client
    working_dir: /app
    volumes:
      # - ./src/xiyan_mcp_server/config.yml:/app/config.yml
      - ./src/mcp_client:/app
      - mcp_xiyan_clent_venv:/app/.venv
    ports:
      - "8013:8013"
    networks:
      - mcp-network
    
    # command: ["python3", "/app/app.py"]
    command: ["tail", "-f", "/dev/null"]
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
    restart: always

networks:
  mcp-network:
    driver: bridge
  
volumes:
  mcp_xiyan_clent_venv:
  mcp_xiyan_server_venv: